// Extends the flat config generated by @nuxt/eslint during `nuxt prepare`,
// which already knows this project's Vue/TypeScript setup and auto-imports.
// Regenerate it with `npm run postinstall` if `.nuxt/` is missing.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  ignores: ['.nuxt/**', '.output/**', 'dist/**', 'data/**', 'node_modules/**'],
})
